name: RolePlayMod
version: 1.0
api-version: 1.19
main: my.roleplay.mod.roleplaymod.RoleplayMod
author: FrankNat
description: Plugin per il roleplay in Minecraft

commands:
  info:
    description: Ottieni informazioni sul plugin
    usage: /info
    permission: roleplaymod.info
    
  me:
    description: Esegui un'azione di roleplay
    usage: /me <messaggio>
    permission: roleplaymod.me
    
  balance:
    description: Ottieni informazioni sul saldo
    usage: /balance
    permission: roleplaymod.balance
    
  pay:
    description: Paga un giocatore
    usage: /pay
    permission: roleplaymod.pay
    
  editbalance:
    description: Modifica il balance di un giocatore
    usage: /editbalance
    permission: roleplaymod.editbalance
    
  showbalance:
    description: Visualizza il saldo di un giocatore
    usage: /showbalance
    permission: roleplaymod.showbalance
    
  tie:
    description: Lega un giocatore
    usage: /tie
    permission: roleplaymod.tie 
    
  untie:
    description: Slega un giocatore
    usage: /untie
    permission: roleplaymod.untie
    
  free:
    description: free da una corda
    usage: /free
    permission: roleplaymod.free 
    
  drag:
    description: drag un giocatore
    usage: /drag
    permission: roleplaymod.drag
    
  searchinventory:
    description: Apri l'inventario di un player
    usage: /searchinventory
    permission: roleplaymod.searchinventory
    
  stats:
    description: Guarda le tue stats
    usage: /stats
    permission: roleplaymod.stats
    
  editstats:
    description: Modifica le stats
    usage: /editstats
    permission: roleplaymod.editstats

permissions:
  roleplaymod.info:
    description: Permetti l'uso del comando /info
    default: true

  roleplaymod.balance:
    description: Permetti l'uso del comando /balance
    default: true
    
  roleplaymod.pay:
    description: Permetti l'uso del comando /pay
    default: true
    
  roleplaymod.showbalance:
    description: Permetti l'uso del comando /showbalance
    default: true
    
  roleplaymod.editbalance:
    description: Permetti l'uso del comando /editbalance
    default: true
    
  roleplaymod.tie:
    description: Permetti l'uso del comando /tie
    default: true
    
  roleplaymod.untie:
    description: Permetti l'uso del comando /untie
    default: true
    
  roleplaymod.free:
    description: Permetti l'uso del comando /free
    default: true
    
  roleplaymod.drag:
    description: Permetti l'uso del comando /drag
    default: true
    
  roleplaymod.searchinventory:
    description: Permetti l'uso del comando /searchinventory
    default: true
    
  roleplaymod.stats:
    description: Permetti l'uso del comando /stats
    default: true
    
  roleplaymod.editstats:
    description: Permetti l'uso del comando /editstats
    default: true