name: RolePlayMod
version: 1.2.2
api-version: 1.19
main: my.roleplay.mod.roleplaymod.RoleplayMod
author: FrankNat
description: Minecraft roleplay plugin

commands:
  info:
    description: Get information about the plugin
    usage: /info
    permission: roleplaymod.info
    
  me:
    description: Perform a roleplay action
    usage: /me <messaggio>
    permission: roleplaymod.me
    
  balance:
    description: Get balance information
    usage: /balance
    permission: roleplaymod.balance
    
  pay:
    description: Pay a player
    usage: /pay
    permission: roleplaymod.pay
    
  editbalance:
    description: Modify a player's balance
    usage: /editbalance
    permission: roleplaymod.editbalance
    
  showbalance:
    description: View a player's balance
    usage: /showbalance
    permission: roleplaymod.showbalance
    
  tie:
    description: Tie a player
    usage: /tie
    permission: roleplaymod.tie 
    
  untie:
    description: Untie a player
    usage: /untie
    permission: roleplaymod.untie
    
  free:
    description: Free yourself from a rope
    usage: /free
    permission: roleplaymod.free 
    
  drag:
    description: Drag a player
    usage: /drag
    permission: roleplaymod.drag
    
  searchinventory:
    description: Open a player's inventory
    usage: /searchinventory
    permission: roleplaymod.searchinventory
    
  stats:
    description: Watch your stats
    usage: /stats
    permission: roleplaymod.stats
    
  editstats:
    description: Modify the stats
    usage: /editstats
    permission: roleplaymod.editstats

permissions:
  roleplaymod.info:
    description: Permetti l'uso del comando /info
    default: true

  roleplaymod.balance:
    description: Permetti l'uso del comando /balance
    default: true
    
  roleplaymod.pay:
    description: Permetti l'uso del comando /pay
    default: true
    
  roleplaymod.showbalance:
    description: Permetti l'uso del comando /showbalance
    default: true
    
  roleplaymod.editbalance:
    description: Permetti l'uso del comando /editbalance
    default: true
    
  roleplaymod.tie:
    description: Permetti l'uso del comando /tie
    default: true
    
  roleplaymod.untie:
    description: Permetti l'uso del comando /untie
    default: true
    
  roleplaymod.free:
    description: Permetti l'uso del comando /free
    default: true
    
  roleplaymod.drag:
    description: Permetti l'uso del comando /drag
    default: true
    
  roleplaymod.searchinventory:
    description: Permetti l'uso del comando /searchinventory
    default: true
    
  roleplaymod.stats:
    description: Permetti l'uso del comando /stats
    default: true
    
  roleplaymod.editstats:
    description: Permetti l'uso del comando /editstats
    default: true